service: slack-apis
frameworkVersion: '2'
custom:
  secrets: ${file(secrets.json)}
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-1
  stage: production
  memorySize: 128 # optional, in MB, default is 1024
  timeout: 6 # optional, in seconds, default is 6
  deploymentBucket:
    name: ${self:custom.secrets.S3_DEPLOYMENT_BUCKET}
  httpApi:
    cors: true
  environment:
    SLACK_API_URL: ${self:custom.secrets.SLACK_API_URL}
    VERIFICATION_TOKEN: ${self:custom.secrets.VERIFICATION_TOKEN}
functions:
  farmingResultsEvents:
    handler: handler.handleFarmingResultsEvents
    name: ${self:service}-farming-results-events
    events:
      - httpApi:
          method: post
          path: /slack/channels/farming-results/events
